version: '3.8'

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - preselect_db
    env_file:
      - ./backend/.env.local
    volumes:
      - ./backend:/app

  preselect_db:
    image: postgres:15.3
    container_name: preselect_db
    env_file:
      - ./backend/.env.local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  admin:
    container_name: preselect-admin
    build: ./frontend/admin
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/admin:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - API_URL=http://backend:8000
      - NEXT_PUBLIC_API=http://localhost:8000

volumes:
   postgres_data:
